# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from lidar_msgs/RecvPacket.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import lidar_msgs.msg

class RecvPacket(genpy.Message):
  _md5sum = "78587254adf0ff3522b94defe9027af8"
  _type = "lidar_msgs/RecvPacket"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """LaserPacket laserpkt
ImuPacket imupkt
GPSPacket gpspkt

================================================================================
MSG: lidar_msgs/LaserPacket
float32[12] Azimuth
float32[192] distance
uint64 timestamp
uint64 id_num

================================================================================
MSG: lidar_msgs/ImuPacket
float32[3] imu_gyro
float32[3] imu_accel
float32[3] imu_magn
float32[3] imu_euler
uint64 timestamp
uint64 id_num

================================================================================
MSG: lidar_msgs/GPSPacket
float64[3] ned_xyz
float64[3] ned_uvw
float64 heading
uint8 gps_sats
uint8 gps_mod
uint64 timestamp
uint64 id_num
"""
  __slots__ = ['laserpkt','imupkt','gpspkt']
  _slot_types = ['lidar_msgs/LaserPacket','lidar_msgs/ImuPacket','lidar_msgs/GPSPacket']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       laserpkt,imupkt,gpspkt

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RecvPacket, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.laserpkt is None:
        self.laserpkt = lidar_msgs.msg.LaserPacket()
      if self.imupkt is None:
        self.imupkt = lidar_msgs.msg.ImuPacket()
      if self.gpspkt is None:
        self.gpspkt = lidar_msgs.msg.GPSPacket()
    else:
      self.laserpkt = lidar_msgs.msg.LaserPacket()
      self.imupkt = lidar_msgs.msg.ImuPacket()
      self.gpspkt = lidar_msgs.msg.GPSPacket()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_12f().pack(*self.laserpkt.Azimuth))
      buff.write(_get_struct_192f().pack(*self.laserpkt.distance))
      _x = self
      buff.write(_get_struct_2Q().pack(_x.laserpkt.timestamp, _x.laserpkt.id_num))
      buff.write(_get_struct_3f().pack(*self.imupkt.imu_gyro))
      buff.write(_get_struct_3f().pack(*self.imupkt.imu_accel))
      buff.write(_get_struct_3f().pack(*self.imupkt.imu_magn))
      buff.write(_get_struct_3f().pack(*self.imupkt.imu_euler))
      _x = self
      buff.write(_get_struct_2Q().pack(_x.imupkt.timestamp, _x.imupkt.id_num))
      buff.write(_get_struct_3d().pack(*self.gpspkt.ned_xyz))
      buff.write(_get_struct_3d().pack(*self.gpspkt.ned_uvw))
      _x = self
      buff.write(_get_struct_d2B2Q().pack(_x.gpspkt.heading, _x.gpspkt.gps_sats, _x.gpspkt.gps_mod, _x.gpspkt.timestamp, _x.gpspkt.id_num))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.laserpkt is None:
        self.laserpkt = lidar_msgs.msg.LaserPacket()
      if self.imupkt is None:
        self.imupkt = lidar_msgs.msg.ImuPacket()
      if self.gpspkt is None:
        self.gpspkt = lidar_msgs.msg.GPSPacket()
      end = 0
      start = end
      end += 48
      self.laserpkt.Azimuth = _get_struct_12f().unpack(str[start:end])
      start = end
      end += 768
      self.laserpkt.distance = _get_struct_192f().unpack(str[start:end])
      _x = self
      start = end
      end += 16
      (_x.laserpkt.timestamp, _x.laserpkt.id_num,) = _get_struct_2Q().unpack(str[start:end])
      start = end
      end += 12
      self.imupkt.imu_gyro = _get_struct_3f().unpack(str[start:end])
      start = end
      end += 12
      self.imupkt.imu_accel = _get_struct_3f().unpack(str[start:end])
      start = end
      end += 12
      self.imupkt.imu_magn = _get_struct_3f().unpack(str[start:end])
      start = end
      end += 12
      self.imupkt.imu_euler = _get_struct_3f().unpack(str[start:end])
      _x = self
      start = end
      end += 16
      (_x.imupkt.timestamp, _x.imupkt.id_num,) = _get_struct_2Q().unpack(str[start:end])
      start = end
      end += 24
      self.gpspkt.ned_xyz = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 24
      self.gpspkt.ned_uvw = _get_struct_3d().unpack(str[start:end])
      _x = self
      start = end
      end += 26
      (_x.gpspkt.heading, _x.gpspkt.gps_sats, _x.gpspkt.gps_mod, _x.gpspkt.timestamp, _x.gpspkt.id_num,) = _get_struct_d2B2Q().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(self.laserpkt.Azimuth.tostring())
      buff.write(self.laserpkt.distance.tostring())
      _x = self
      buff.write(_get_struct_2Q().pack(_x.laserpkt.timestamp, _x.laserpkt.id_num))
      buff.write(self.imupkt.imu_gyro.tostring())
      buff.write(self.imupkt.imu_accel.tostring())
      buff.write(self.imupkt.imu_magn.tostring())
      buff.write(self.imupkt.imu_euler.tostring())
      _x = self
      buff.write(_get_struct_2Q().pack(_x.imupkt.timestamp, _x.imupkt.id_num))
      buff.write(self.gpspkt.ned_xyz.tostring())
      buff.write(self.gpspkt.ned_uvw.tostring())
      _x = self
      buff.write(_get_struct_d2B2Q().pack(_x.gpspkt.heading, _x.gpspkt.gps_sats, _x.gpspkt.gps_mod, _x.gpspkt.timestamp, _x.gpspkt.id_num))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.laserpkt is None:
        self.laserpkt = lidar_msgs.msg.LaserPacket()
      if self.imupkt is None:
        self.imupkt = lidar_msgs.msg.ImuPacket()
      if self.gpspkt is None:
        self.gpspkt = lidar_msgs.msg.GPSPacket()
      end = 0
      start = end
      end += 48
      self.laserpkt.Azimuth = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=12)
      start = end
      end += 768
      self.laserpkt.distance = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=192)
      _x = self
      start = end
      end += 16
      (_x.laserpkt.timestamp, _x.laserpkt.id_num,) = _get_struct_2Q().unpack(str[start:end])
      start = end
      end += 12
      self.imupkt.imu_gyro = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      start = end
      end += 12
      self.imupkt.imu_accel = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      start = end
      end += 12
      self.imupkt.imu_magn = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      start = end
      end += 12
      self.imupkt.imu_euler = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      _x = self
      start = end
      end += 16
      (_x.imupkt.timestamp, _x.imupkt.id_num,) = _get_struct_2Q().unpack(str[start:end])
      start = end
      end += 24
      self.gpspkt.ned_xyz = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=3)
      start = end
      end += 24
      self.gpspkt.ned_uvw = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=3)
      _x = self
      start = end
      end += 26
      (_x.gpspkt.heading, _x.gpspkt.gps_sats, _x.gpspkt.gps_mod, _x.gpspkt.timestamp, _x.gpspkt.id_num,) = _get_struct_d2B2Q().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_12f = None
def _get_struct_12f():
    global _struct_12f
    if _struct_12f is None:
        _struct_12f = struct.Struct("<12f")
    return _struct_12f
_struct_192f = None
def _get_struct_192f():
    global _struct_192f
    if _struct_192f is None:
        _struct_192f = struct.Struct("<192f")
    return _struct_192f
_struct_2Q = None
def _get_struct_2Q():
    global _struct_2Q
    if _struct_2Q is None:
        _struct_2Q = struct.Struct("<2Q")
    return _struct_2Q
_struct_d2B2Q = None
def _get_struct_d2B2Q():
    global _struct_d2B2Q
    if _struct_d2B2Q is None:
        _struct_d2B2Q = struct.Struct("<d2B2Q")
    return _struct_d2B2Q
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
